AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  image-gen-26

Globals:
  Function:
    Timeout: 30
    MemorySize: 128

Resources:
  GenerateImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      CodeUri: hello_world
      Environment:
        Variables:
          BUCKET_NAME: "pgr301-couch-explorers"
          CANDIDATE_NUMBER: "26"
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - "s3:PutObject"
              Resource:
                - "arn:aws:s3:::pgr301-couch-explorers/*"
            - Effect: Allow
              Action:
                - "bedrock:InvokeModel"
              Resource:
                - "arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-image-generator-v1"
      Events:
        GenerateImageAPI:
          Type: Api
          Properties:
            Path: /generate-image
            Method: post

Outputs:
  GenerateImageApi:
    Description: "API Gateway endpoint URL for the Generate Image function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/generate-image/"
  GenerateImageFunction:
    Description: "Generate Image Lambda Function ARN"
    Value: !GetAtt GenerateImageFunction.Arn
  GenerateImageFunctionIamRole:
    Description: "Implicit IAM Role created for Generate Image function"
    Value: !GetAtt GenerateImageFunctionRole.Arn

