name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Sjekk ut koden fra repoet
      - name: Checkout repository
        uses: actions/checkout@v4

      # Logg inn på Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Bygg Docker image
      - name: Build Docker image
        run: |
          docker build -f java_sqs_client/Dockerfile -t ezzoali/java-sqs-client:latest java_sqs_client

      # Push Docker image til Docker Hub
      - name: Push Docker image
        run: |
          docker push ezzoali/java-sqs-client:latest
