name: Terraform Deploy

on:
  push:
    branches:
      - main
      - '**'  # Trigger for all branches

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      # Configure AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: infra  

      # Terraform Plan for non-main branches
      - name: Terraform Plan
        if: github.ref != 'refs/heads/main'
        run: terraform plan
        working-directory: infra  

      # Terraform Apply for main branch
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
        working-directory: infra  
